In [69]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [70]:
arr = np.array(42)

print(arr) 

42


In [71]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [72]:
arr = np.array([1, 2, 3, 4])

print(arr[0]) 

1


In [73]:
arr = np.array([1, 2, 3, 4])

print(arr[2]) 

3


In [74]:
arr = np.array([1, 2, 3, 4])

print(arr[1]) 

2


In [75]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7
